[package]
name = "artillery"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.142"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
